jobs = [
    # Real Jobs
    "Accountant",
    "Actor",
    "Astronaut",
    "Baker",
    "Barista",
    "Biologist",
    "Chef",
    "Civil engineer",
    "Comedian",
    "Computer programmer",
    "Dancer",
    "Data analyst",
    "Detective",
    "Doctor",
    "Economist",
    "Electrician",
    "Farmer",
    "Firefighter",
    "Flight attendant",
    "Florist",
    "Graphic designer",
    "Historian",
    "Illustrator",
    "Journalist",
    "Judge",
    "Lawyer",
    "Librarian",
    "Magician",
    "Marketing manager",
    "Musician",
    "Nurse",
    "Painter",
    "Pharmacist",
    "Photographer",
    "Pilot",
    "Police officer",
    "Politician",
    "Professor",
    "Psychologist",
    "Receptionist",
    "Sales representative",
    "Scientist",
    "Sculptor",
    "Software developer",
    "Surgeon",
    "Teacher",
    "Veterinarian",
    "Waiter/Waitress",
    "Web designer",
    "Writer",

    # Make-believe Jobs
    "Dragon tamer",
    "Fairy godmother",
    "Jedi knight",
    "Ninja",
    "Pirate",
    "Space cowboy",
    "Superhero",
    "Time traveler",
    "Unicorn caretaker",
    "Wizard",
    "Account manager",
    "Archaeologist",
    "Architect",
    "Automotive mechanic",
    "Bank teller",
    "Biomedical engineer",
    "Bus driver",
    "Carpenter",
    "Chemist",
    "Construction worker",
    "Dental hygienist",
    "Economist",
    "Electrical engineer",
    "Event planner",
    "Fashion designer",
    "Financial analyst",
    "Fitness instructor",
    "Game developer",
    "Geologist",
    "Hair stylist",
    "Human resources manager",
    "Industrial designer",
    "Interior designer",
    "IT consultant",
    "Journalist",
    "Landscaper",
    "Marketing coordinator",
    "Mechanical engineer",
    "Music producer",
    "Occupational therapist",
    "Paralegal",
    "Pharmacist",
    "Physical therapist",
    "Police detective",
    "Product manager",
    "Registered nurse",
    "Social media manager",
    "Software engineer",
    "Sports coach",
    "Teacher assistant",
    "Veterinarian technician",
    "Wedding planner",
    "Zookeeper",
    "Alien hunter",
    "Bounty hunter",
    "Cryptozoologist",
    "Dragon trainer",
    "Fairy tale writer",
    "Ghost hunter",
    "Imaginary friend",
    "Jedi master",
    "Mermaid/merman",
    "Monster truck driver",
    "Pirate captain",
    "Space explorer",
    "Super villain",
    "Time traveler",
    "UFO investigator",
    "Vampire hunter",
    "Wizarding professor"
]


emotions = [
    "Joy",
    "Sadness",
    "Anger",
    "Fear",
    "Love",
    "Surprise",
    "Disgust",
    "Excitement",
    "Guilt",
    "Pride",
    "Hope",
    "Anxiety",
    "Contentment",
    "Envy",
    "Confusion",
    "Jealousy",
    "Regret",
    "Curiosity",
    "Embarrassment",
    "Frustration",
    "Amazement",
    "Boredom",
    "Happiness",
    "Sorrow",
    "Rage",
    "Dread",
    "Affection",
    "Anticipation",
    "Delight",
    "Disappointment",
    "Elation",
    "Shame",
    "Remorse",
    "Satisfaction",
    "Serenity",
    "Pleasure",
    "Desire",
    "Aggression",
    "Hostility",
    "Loneliness",
    "Hopelessness",
    "Awe",
    "Nervousness",
    "Worry",
    "Peace",
    "Disinterest",
    "Delight",
    "Hurt",
    "Hate",
    "Disappointment",
    "Grief",
    "Yearning",
    "Panic",
    "Euphoria",
    "Contempt",
    "Gratitude",
    "Calm",
    "Insecurity",
    "Resentment",
    "Optimism",
    "Melancholy",
    "Apprehension",
    "Skepticism",
    "Affection",
    "Revulsion",
    "Longing",
    "Distrust",
    "Agony",
    "Nostalgia",
    "Lust",
    "Zeal",
    "Apathy",
    "Repulsion",
    "Gratitude",
    "Patience",
    "Curiosity",
    "Unease",
    "Fascination",
    "Eagerness"
]


relationship = [
    "Parent",
    "Sibling",
    "Grandparent",
    "Aunt",
    "Uncle",
    "Cousin",
    "Spouse",
    "Child",
    "Grandchild",
    "In-law",
    "Step-parent",
    "Step-sibling",
    "Step-child",
    "Step-grandparent",
    "Half-sibling",
    "Adoptive parent",
    "Adopted child",
    "Godparent",
    "Godchild",
    "Best friend",
    "Soulmate",
    "Roommate",
    "Co-worker",
    "Boss",
    "Employee",
    "Teacher",
    "Student",
    "Mentor",
    "Mentee",
    "Neighbor",
    "Classmate",
    "Childhood friend",
    "Rival",
    "Enemy",
    "Ally",
    "Secret admirer",
    "Long-lost relative",
    "Ancestor",
    "Descendant",
    "Guardian",
    "Ward",
    "Hero",
    "Sidekick",
    "Superior officer",
    "Subordinate",
    "Master",
    "Apprentice",
    "Servant",
    "Employer",
    "Employee",
    "Doctor",
    "Patient",
    "Nurse",
    "Therapist",
    "Psychiatrist",
    "Psychologist",
    "Coach",
    "Athlete",
    "Teammate",
    "Rival athlete",
    "Fan",
    "Idol",
    "Teacher's pet",
    "Principal",
    "Superintendent",
    "Schoolmate",
    "Secret agent",
    "Spy",
    "Crime boss",
    "Henchman",
    "Superhero",
    "Villain",
    "Wizard",
    "Apprentice wizard",
    "Fairy",
    "Magical creature",
    "Alien",
    "Robot",
    "Artificial intelligence",
    "Time traveler",
    "Parallel universe counterpart",
    "Mythical being",
    "Dragon",
    "Vampire",
    "Werewolf",
    "Ghost",
    "Mermaid/Merman",
    "God/Goddess",
    "Demigod/Demigoddess",
    "Fictional character",
    "Imaginary friend",
    "Virtual reality companion",
    "Video game avatar",
    "Pet",
    "Animal companion",
    "Guardian angel",
    "Genie",
    "Wish granter",
    "Muse",
    "Fellow adventurer",
    "Comic book hero",
    "Novel protagonist",
    "Movie character",
    "Cartoon character",
    "Time-traveling companion",
    "Archaeological partner",
    "Writing collaborator",
    "Artistic muse",
    "Business partner",
    "Rival entrepreneur",
    "Investor",
    "Apprentice",
    "Sensei",
    "Cosplay partner",
    "Fencing adversary",
    "Sailing crewmate",
    "Musical bandmate",
    "Dance partner",
    "Karaoke duet partner",
    "Travel buddy",
    "Research partner",
    "Photography model",
    "Art classmate",
    "Online gaming teammate",
    "Virtual reality co-explorer",
    "Conspiracy theorist",
    "Alien abductee",
    "Interstellar pen pal",
    "Undercover agent",
    "Crime-fighting partner",
    "Historical figure clone",
    "Adventuring companion",
    "Parallel universe doppelgänger",
    "Comic book collector",
    "Novel writing club member",
    "Scriptwriting partner",
    "Film production collaborator",
    "LARPing ally",
    "Zombie apocalypse survival partner",
    "Paranormal investigator",
    "Radio show co-host",
    "Podcast co-host",
    "Blogging buddy",
    "Fashion stylist",
    "Makeup artist",
    "Gardening partner",
    "Cooking buddy",
    "Baking collaborator",
    "Fitness trainer",
    "Yoga partner",
    "Meditation group member",
    "Volunteering teammate",
    "Charity event organizer",
    "Fundraising partner",
    "Book club member",
    "Chess rival",
    "Magic trick assistant",
    "Escape room partner",
    "Board game enthusiast",
    "Role-playing game co-player",
    "Archery teammate",
    "Skydiving buddy",
    "Rock climbing partner",
    "Surfing companion",
    "Scuba diving buddy",
    "Snorkeling buddy",
    "Cycling partner",
    "Hiking buddy",
    "Road trip companion",
    "Motorcycle riding buddy",
    "Camping mate",
    "Nature exploration partner",
    "Geocaching teammate",
    "Ghost hunting buddy",
    "Museum exploration partner",
    "Amusement park pal",
    "Aquarium visit companion",
    "Planetarium show partner",
    "Concertgoer",
    "Movie marathon partner",
    "Binge-watching buddy",
    "Theater play companion",
    "Stand-up comedy show attendee",
    "Art gallery visitor",
    "Fashion show attendee",
    "Wine tasting buddy",
    "Coffee shop aficionado",
    "Tea ceremony partner",
    "Traveling salesman",
    "Secret agent handler",
    "Underground informant",
    "Cybersecurity partner",
    "Holographic companion",
    "Virtual assistant",
    "Android companion",
    "Time-limited clone",
    "Adventure game character",
    "Dream character",
    "Imagination buddy",
    "Writing prompt generator",
    "Storytelling collaborator",
    "Riddle-solving partner",
    "AI conversation partner",
    "Inventor's assistant",
    "Scientific experiment collaborator",
    "Lab partner",
    "Time-loop partner",
    "Superpower training buddy",
    "Magical artifact guardian",
    "Fairy tale character",
    "Mythical kingdom ally",
    "Quest companion",
    "Space travel crewmate",
    "Interdimensional explorer",
    "Alternate history explorer",
]


actions = [
    "Reading a mystery novel",
    "Writing a journal entry",
    "Painting a landscape with acrylics",
    "Solving a Rubik's Cube",
    "Cooking a traditional Italian pasta dish",
    "Running a half-marathon",
    "Building a sandcastle on a tropical beach",
    "Playing the piano",
    "Dancing salsa at a local club",
    "Hiking to the top of a snow-capped mountain",
    "Swimming with sharks in the Galapagos Islands",
    "Skydiving over the Grand Canyon",
    "Performing a stand-up comedy routine",
    "Planting a vegetable garden in the backyard",
    "Learning to speak Japanese fluently",
    "Playing a multiplayer online battle game",
    "Watching a live improvisational comedy show",
    "Singing karaoke with friends",
    "Ice skating at Rockefeller Center in New York City",
    "Exploring an abandoned castle",
    "Scuba diving in the Great Barrier Reef",
    "Writing a heartfelt letter to a loved one",
    "Creating a custom engagement ring",
    "Building and flying a remote-controlled drone",
    "Photographing the northern lights",
    "Designing a mobile app for a local business",
    "Sculpting a life-size statue from clay",
    "Trekking through the Amazon rainforest",
    "Embarking on a cross-country road trip",
    "Stargazing with a telescope in the desert",
    "Bungee jumping off a suspension bridge",
    "Practicing yoga on a serene beach",
    "Making a delicious homemade lasagna",
    "Playing a competitive chess tournament",
    "Volunteering at a homeless shelter",
    "Attending a live jazz concert",
    "Taking a gourmet cooking class",
    "Exploring an underwater cave",
    "Creating a viral TikTok video",
    "Attending a cosplay convention",
    "Building a treehouse in the backyard",
    "Learning to juggle with flaming torches",
    "Doing a stand-up paddleboarding yoga session",
    "Riding a thrilling roller coaster",
    "Building a fully functional robot from scratch",
    "Doing a DIY home improvement project: remodeling the kitchen",
    "Exploring a virtual reality game with friends",
    "Writing a compelling short story",
    "Taking a pottery class and making ceramic bowls",
    "Flying a kite at a picturesque beach",
    "Going on a camping trip in the wilderness",
    "Starting a personal blog and writing weekly articles",
    "Practicing meditation in a peaceful garden",
    "Planning and organizing a surprise party for a friend",
    "Playing a strategy board game with a group of friends",
    "Trying a bold new haircut and hair color",
    "Creating a scrapbook of cherished memories",
    "Going on a city-wide treasure hunt with clues",
    "Learning to play golf and joining a local golf club",
    "Having a delightful picnic in a blooming cherry blossom garden",
    "Taking a photography trip to capture stunning landscapes",
    "Designing a fashion collection inspired by nature",
    "Playing a thrilling game of laser tag with friends",
    "Joining a book club and engaging in lively discussions",
    "Building an intricate model train set with realistic landscapes",
    "Embarking on a solo backpacking trip across Europe",
    "Trying out a new recipe for homemade sushi rolls",
    "Writing and performing an original song at a local open mic night",
    "Visiting a trampoline park and mastering impressive flips",
    "Creating a hilarious comic",
    "Summoning a fire-breathing dragon",
    "Performing a necromantic ritual",
    "Embarking on a quest to find a cursed artifact",
    "Engaging in a bloody sword fight",
    "Cooking a potion with eye of newt and dragon scales",
    "Running through a haunted forest at midnight",
    "Building a mechanical golem",
    "Dancing with skeletons in a macabre ballroom",
    "Exploring a twisted labyrinth filled with traps",
    "Creating a grotesque sculpture from monster remains",
    "Hiking through a forest of carnivorous plants",
    "Swimming in a pool of vampire blood",
    "Skydiving into a mystical realm",
    "Performing a dark ritual to communicate with spirits",
    "Painting a portrait of a ghostly apparition",
    "Solving riddles to unlock the gates of an enchanted castle",
    "Cooking a feast for a gathering of witches and warlocks",
    "Running from a horde of zombies in a post-apocalyptic world",
    "Building an eldritch contraption to channel dark energies",
    "Dancing with mythical creatures under a full moon",
    "Hiking through a wasteland inhabited by mutant creatures",
    "Swimming in a lake of bubbling lava",
    "Skydiving onto a floating island in the sky",
    "Performing a forbidden spell to resurrect a loved one",
    "Planting a garden of carnivorous plants",
    "Learning to speak the language of mythical beasts",
    "Playing a multiplayer online game with supernatural powers",
    "Watching a live performance by a vampire illusionist",
    "Singing haunting melodies to tame wild spirits",
    "Ice skating on a frozen lake in the underworld",
    "Exploring an ancient tomb filled with cursed treasures",
    "Scuba diving in an underwater graveyard",
    "Writing a grimoire of dark magic spells",
    "Creating a twisted sculpture made of twisted limbs",
    "Trekking through a haunted swamp in search of a lost relic",
    "Embarking on a cross-dimensional road trip",
    "Stargazing at constellations that tell prophecies",
    "Bungee jumping into a bottomless abyss",
    "Practicing yoga to attain supernatural flexibility",
    "Making a delicious potion with magical ingredients",
    "Playing a competitive chess game against a demon",
    "Volunteering at a haunted asylum",
    "Attending a live concert of a ghostly symphony",
    "Taking a cooking class on preparing ghoulish dishes",
    "Exploring an ancient underwater city",
    "Creating a viral TikTok video featuring bizarre illusions",
    "Attending a masquerade ball in a haunted mansion",
    "Building a treehouse in a haunted forest",
    "Learning to juggle with enchanted objects",
    "Doing a stand-up comedy routine for an audience of monsters",
    "Riding a roller coaster through a haunted theme park",
    "Building a fully functional robotic monster",
    "Doing a DIY home improvement project to create a mad scientist lab",
    "Exploring a virtual reality game with nightmarish creatures",
    "Writing a spine-chilling horror story",
    "Taking a pottery class and making creepy clay figurines",
    "Flying on a broomstick through a dark and stormy night",
    "Going on a camping trip in a cursed forest",
    "Starting a personal blog dedicated to bizarre and supernatural encounters",
    "Practicing meditation to commune with otherworldly beings",
    "Planning and organizing a surprise",
    "Practicing synchronized swimming with a group of penguins",
    "Building a time machine out of cardboard boxes",
    "Dancing the Macarena in a crowded shopping mall",
    "Playing a kazoo in a marching band",
    "Attempting to break the world record for the longest time balancing a spoon on your nose",
    "Joining a clown college and learning how to juggle rubber chickens",
    "Organizing a prank war with friends",
    "Hopping on one foot for an entire day",
    "Creating a funny viral video with a dancing dog",
    "Attending a stand-up comedy workshop and performing a routine",
    "Playing hide-and-seek in a supermarket",
    "Embarking on a quest to find the funniest joke in the world",
    "Attempting to break the world record for the most socks worn at once",
    "Building a makeshift roller coaster in the backyard",
    "Trying to ride a unicycle while juggling bowling pins",
    "Organizing a silly fashion show with outfits made from recycled materials",
    "Participating in a pie-eating contest",
    "Creating a hilarious lip-sync video with friends",
    "Joining a laughter yoga class and laughing uncontrollably",
    "Trying to balance a spoon on your nose while standing on one leg",
    "Organizing a water balloon fight in the neighborhood",
    "Attempting to break the world record for the loudest burp",
    "Building a giant pillow fort in the living room",
    "Dressing up as a superhero and patrolling the streets",
    "Playing a game of hide-and-seek in a library",
    "Attempting to break the world record for the longest time spent wearing mismatched socks",
    "Organizing a silly dance-off competition",
    "Creating a prank YouTube channel and filming hilarious pranks",
    "Participating in a potato sack race",
    "Building a mini-golf course in the backyard with household objects",
    "Trying to break the world record for the highest tower made of playing cards",
    "Organizing a funny talent show with friends",
    "Attempting to balance a spoon, a fork, and a knife on your face simultaneously",
    "Creating a goofy puppet show and performing for family and friends",
    "Joining a comedy improv group and performing hilarious skits",
    "Dressing up as a dinosaur and surprising people at the park",
    "Attempting to break the world record for the longest time spent hopping on a pogo stick",
    "Organizing a silly obstacle course in the backyard",
    "Creating a funny YouTube series where you review bizarre snacks",
    "Participating in a silly hat competition",
    "Building a human pyramid with friends",
    "Trying to break the world record for the most marshmallows stuffed in your mouth",
    "Organizing a funny face contest",
    "Creating a homemade comic strip and sharing it with friends",
    "Joining a comedy writing workshop and crafting hilarious jokes",
    "Dressing up as a superhero and performing random acts of kindness",
    "Attempting to break the world record for the fastest time to assemble a jigsaw puzzle",
    "Organizing a laughter yoga session with friends",
    "Creating a funny photo booth with silly props",
    "Participating in a game of charades",
    "Building a giant paper airplane and launching it from a hilltop",
    "Trying to break the world record for the most socks mismatched and worn outside",
    "Organizing a funny pet fashion show",
    "Creating a silly TikTok dance and challenging others to do it",
    "Crying alone in a dark room",
    "Writing a heartfelt letter to a lost loved one",
    "Sitting by a gravestone, reminiscing about the past",
    "Watching a sad movie and sobbing uncontrollably",
    "Listening to a melancholic song and feeling a deep sense of sorrow",
    "Writing a diary entry about feelings of loneliness",
    "Standing in the rain, feeling the weight of sadness",
    "Hugging a stuffed animal for comfort",
    "Lying in bed, unable to sleep due to a broken heart",
    "Attending a therapy session to process emotional pain",
    "Visiting a place that holds bittersweet memories",
    "Looking at old photographs and longing for happier times",
    "Writing a poem about heartbreak and loss",
    "Sitting at an empty table, missing someone who is no longer there",
    "Listening to a voicemail from a departed loved one",
    "Gazing at a sunset, feeling a sense of longing",
    "Writing a goodbye letter to a friend who has passed away",
    "Sitting in a park, watching children play and feeling a sense of emptiness",
    "Wandering through a museum, feeling overwhelmed by the beauty and sadness of art",
    "Attending a support group for those who have experienced loss",
    "Lying on the floor, staring at the ceiling in a state of despair",
    "Writing a song about heartbreak and unrequited love",
    "Sitting on a park bench, watching couples walk by and feeling a sense of longing",
    "Listening to a sad story from a friend and empathizing with their pain",
    "Sitting in a hospital waiting room, anxiously awaiting news of a loved one",
    "Writing a eulogy for a dear friend or family member",
    "Holding onto a cherished memento and shedding tears of nostalgia",
    "Attending a memorial service and finding solace in shared grief",
    "Standing at a train station, bidding farewell to someone you love",
    "Writing a journal entry about feeling lost and disconnected",
    "Sitting in an empty room, surrounded by reminders of a lost relationship",
    "Listening to a sad melody on a rainy day, tears streaming down your face",
    "Lying in bed, wrapped in sadness and unable to face the outside world",
    "Writing a letter to an estranged family member, expressing regret and longing",
    "Sitting in a coffee shop, observing happy couples and feeling a deep sense of longing",
    "Visiting a place of personal significance, overwhelmed by memories of happier times",
    "Writing a story that explores themes of tragedy and heartbreak",
    "Standing at the edge of a cliff, contemplating the weight of sorrow",
    "Listening to a voicemail from a lost friendship, feeling a pang of sadness",
    "Sitting in a theater, watching a heart-wrenching play and shedding tears",
    "Writing a diary entry about the pain of unrequited love",
    "Sitting in a waiting room, anxiously hoping for positive news",
    "Listening to a sad symphony, feeling the music resonate with inner sadness",
    "Writing a heartfelt letter to a parent, expressing unresolved emotions",
    "Sitting alone at a restaurant, watching couples enjoy their meals and feeling a deep sense of loneliness",
    "Visiting a childhood home, overcome with nostalgia and a sense of loss",
    "Writing a poem about the fragility of life and the inevitability of loss",
    "Standing in front of a grave, feeling the weight of grief",
    ]

writings = [
    "Ancient prophecy",
    "Spellbook incantation",
    "Tome of legends",
    "Wizard's grimoire",
    "Scroll of enchantments",
    "Dragon's journal",
    "Elven ballad",
    "Fairy tale",
    "Dwarven runes",
    "Magical recipe",
    "Sorcerer's spell scroll",
    "Mythical creature guide",
    "Necromancer's diary",
    "Enchanted map",
    "Celestial prophecy",
    "Song of the merfolk",
    "Goblin folklore",
    "Werewolf chronicles",
    "Angel's letter to the heavens",
    "Orcish war chants",
    "Wizard's letter to an apprentice",
    "Troll riddle",
    "Spellcasting instructions",
    "Knight's code of honor",
    "Potion brewing manual",
    "Fairy dust recipe",
    "Druid's nature diary",
    "Magical artifact catalog",
    "Quest log",
    "Sorceress' secret diary",
    "Divination guidebook",
    "Invisible ink correspondence",
    "Cursed artifact warning",
    "Epic battle poem",
    "Leprechaun's hidden treasure map",
    "Gargoyle's stone tablet inscription",
    "Elven queen's decree",
    "Mermaid's underwater song",
    "Wizard's alchemical formula",
    "Fountain of youth legend",
    "Centaur's forest exploration log",
    "Ghostly apparition's message",
    "Chimera's creature compendium",
    "Fairy queen's proclamation",
    "Siren's seductive song",
    "Magical contract",
    "Enchanted forest guide",
    "Dragon rider's journal",
    "Witch's spell recipe",
    "Unicorn's sacred hymn",
    "Phoenix's rebirth poem",
    "Wizard's prophecy scroll",
    "Memo",
    "Journal entry",
    "Manifesto",
    "Manifest",
    "Field report",
    "Opinion piece",
    "Official statement",
    "Conference paper",
    "Instruction manual",
    "Research proposal",
    "Mission statement",
    "Press release",
    "Treatment",
    "White paper",
    "Public service announcement",
    "Story outline",
    "Journal article",
    "Technical specification",
    "Exposé",
    "Slogan",
    "Grant proposal",
    "Design brief",
    "Mission briefing",
    "Personal reflection",
    "Advertisement copy",
    "Design document",
    "Letter of recommendation",
    "Script treatment",
    "Project proposal",
    "Essay",
    "Concept note",
    "Executive summary",
    "Project plan",
    "Case study",
    "Speech transcript",
    "Campaign slogan",
    "Meeting minutes",
    "Product description",
    "Lecture notes",
    "Job application",
    "Team charter",
    "Policy memo",
    "Creative brief",
    "Contract",
    "User manual",
    "Business plan",
    "Website content",
    "Presentation slides",
    "Infographic",
    "Book preface",
    "Survey questionnaire",
    "Code documentation",
    "Procedural manual",
    "Mission briefing",
    "News report",
    "Feature article",
    "Business letter",
    "Game rulebook",
    "Curriculum vitae",
    "Brochure",
    "Script dialogue",
    "Event program",
    "Curatorial statement",
    "Advertisement storyboard",
    "Legal contract",
    "User interface copy",
    "Grant application",
    "Recipe",
    "Film treatment",
    "Workshop agenda",
    "Product review",
    "Pitch deck",
    "Financial report",
    "Exhibition catalog",
    "Installation instructions",
    "Social media post",
    "Annual report",
    "Cover letter",
    "Interactive story script",
    "Memoir excerpt",
    "Photography portfolio",
    "Video game narrative",
    "Lab report",
    "Proposal outline",
    "Autobiographical sketch",
    "Character backstory",
    "Roadmap",
    "Campaign strategy",
    "Comedy sketch",
    "Surrealist poem",
    "Historical account",
    "Comic strip",
    "Play script",
    "Scientific analysis",
    "Satirical article",
    "Newsletter",
    "Story pitch",
    "Interview transcript",
    "Product packaging copy",
    "Radio advertisement",
    "Job description",
    "Ethics statement",
    "Public speaking guide",
    "Screenplay treatment",
    "Children's storybook",
    "Guidebook",
    "Recipe book",
    "Self-help book",
    "Novel",
    "Short story",
    "Autobiography",
    "Poetry anthology",
    "Adventure novel",
    "Biography",
    "Journal or diary",
    "Play",
    "Mystery novel",
    "Screenplay",
    "Comic book",
    "Travelogue",
    "Magazine article",
    "Business proposal",
    "Photography book",
    "Art critique",
    "Manifesto",
    "Guidebook",
    "Fashion magazine article",
    "Research paper",
    "Sports commentary",
    "Textbook",
    "Screenplay",
    "Picture book",
    "Textbook",
    "Self-help book",
    "Memoir",
    "Horror story",
    "Play for young audiences",
    "Interview",
    "Film script",
    "Awareness pamphlet",
    "Writing guidebook",
    "Fantasy series",
    "Legal thriller novel",
    "Children's book",
    "Instruction manual",
    "Science magazine article",
    "Social commentary blog",
    "Comic strip series",
    "Memoir",
    "Poetry collection",
    "Workbook",
    "Detective novella",
    "Dystopian novel",
    "Romantic screenplay",
    "Motivational speech",
    "Fashion design portfolio",
    "Podcast series",
    "Opinion column",
    "Research paper",
    "Food and restaurant review blog",
    "Graphic novel",
    "Sports autobiography",
    "Parenting guidebook",
    "Role-playing game rulebook",
    "TV show script",
    "Screenplay",
    "Medical research paper",
    "Documentary script",
    "Photography book",
    "Horror anthology",
    "Science experiment guide",
    "Romantic novella",
    "Business blog",
    "World-building guide",
    "Non-fiction book",
    "Cooking show script",
    "Marketing guide",
    "Memoir",
    "Legal drama screenplay",
    "Animated video series script",
    "Health and wellness blog",
    "Psychological thriller novel",
    "Fashion illustration portfolio",
    "Children's mobile app",
    "Audio drama script",
    "Sports strategy guide",
    "Marketing research report",
    "Poetry anthology",
    "Musician's guidebook",
    "Romantic suspense novel",
    "Children's board game instructions",
    "Documentary narration script",
    "Essay collection",
    "Photography exhibition catalog",
    "Medical journal article",
    "Podcast series",
    "Fashion trend analysis report",
    "Science video script",
    "Meditation guide",
    "Video game dialogue script",
    "Campaign speech",
    "Children's coloring book",
    "Poetry chapbook",
    "Science experiment kit manual",
    "Sports magazine article",
    "Country song",
    "Greeting card",
    "Email",
    "Report for your boss",
    "Love letter",
    "Newspaper editorial",
    "Blog post",
    "Fantasy novel",
    "Scientific research paper",
    "Breakup letter",
    "Marketing copy",
    "Comedy sketch",
    "Speech for a special occasion",
    "News article",
    "Personal essay",
    "Government policy document",
    "Horror screenplay",
    "Song lyrics",
    "Academic thesis",
    "Restaurant menu",
    "Web content for an e-commerce site",
    "Science fiction novella",
    "Horror short story",
    "Crime scene report",
    "Autopsy report",
    "Serial killer's diary",
    "Zombie survival guide",
    "Dark poetry collection",
    "Supernatural thriller screenplay",
    "Cursed object description",
    "Cannibalistic tribe folklore",
    "Vampire love story",
    "Ghost hunter's journal",
    "Witch's spellbook",
    "Haunted house investigation log",
    "Psychological thriller novel",
    "Slasher film screenplay",
    "Book of cursed rituals",
    "Dark fantasy novella",
    "Murder mystery novel",
    "Torture chamber blueprints",
    "Werewolf transformation guide",
    "Demonology encyclopedia",
    "Voodoo priestess's memoir",
    "Sinister fairy tale collection",
    "Crime novel with graphic details",
    "Mythical creature autopsy guide",
    "Gruesome murder scene sketchbook",
    "Psychological horror screenplay",
    "Lovecraftian short stories",
    "Zombie apocalypse survival journal",
    "Grim reaper's diary",
    "Evil sorcerer's grimoire",
    "Dark fantasy graphic novel",
    "Serial killer's manifesto",
    "Cult initiation ceremony transcript",
    "Supernatural crime thriller novel",
    "Monster hunter's field notes",
    "Disturbing folklore anthology",
    "Necromancer's spell scroll",
    "Suspenseful horror movie script",
    "Bone-chilling ghost stories",
    "Splatterpunk novel",
    "Cursed family tree genealogy",
    "Psychological torment poetry collection",
    "Dark ritual instruction manual",
    "Demon possession firsthand account",
    "Distorted reality novel",
    "Ghost ship captain's log",
    "Lovecraftian cosmic horror novella",
    "Disturbing urban legends compilation",
    "Haunting memoir of a survivor",
    "Erotic romance novel",
    "Sensual poetry collection",
    "BDSM lifestyle guide",
    "Steamy short stories anthology",
    "Taboo love affair memoir",
    "Erotic photography portfolio",
    "Seductive letter to a lover",
    "Adult party game instructions",
    "Naughty comic strip series",
    "Sex advice column",
    "Swinger's lifestyle guidebook",
    "Kama Sutra illustrated manual",
    "Provocative blog about intimacy",
    "Racy screenplay for an adult film",
    "Erotic novella series",
    "Sultry love letters collection",
    "Adult toy catalog descriptions",
    "Seduction techniques handbook",
    "Erotic fantasy role-playing script",
    "Personal memoir exploring sexuality",
    "Steamy chat transcripts",
    "Erotica poetry chapbook",
    "BDSM scene negotiation guide",
    "Sensual massage tutorial",
    "Fetish-themed short story collection",
    "Swinger's club membership brochure",
    "Erotic audio storytelling script",
    "Exotic dancer's diary",
    "Provocative art exhibition catalog",
    "Sex-positive blog exploring desires",
    "Erotic haiku anthology",
    "Sensual playlist creation guide",
    "Polyamory relationship memoir",
    "Erotic hypnosis script",
    "Erotic travel memoir",
    "Naughty party planner's guide",
    "Intimate photography instruction manual",
    "Steamy confession forum threads",
    "Seductive fashion editorial",
    "Adult-themed card game instructions"
]

